/*
GCOM API

Grafana.com API (public).  Looking for GCOM API client packages? You can find them at [grafana-com-public-clients](https://github.com/grafana/grafana-com-public-clients) repository.  If you have any questions, please contact support in the Grafana Cloud UI.  This spec is in *Beta* stage, so use it with caution: - Not all endpoint responses are properly typed for the time being. - Some request parameter types may not be precise

API version: public
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the StackUpdateRequestV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StackUpdateRequestV1{}

// StackUpdateRequestV1 struct for StackUpdateRequestV1
type StackUpdateRequestV1 struct {
	// protection active or not for the stack
	DeleteProtection NullableBool `json:"deleteProtection,omitempty"`
	// description of the stack
	Description NullableString `json:"description,omitempty"`
	// labels to add to the stack
	Labels *map[string]string `json:"labels,omitempty"`
	// of the stack
	Name NullableString `json:"name,omitempty"`
	// slug of the stack
	Slug NullableString `json:"slug,omitempty"`
	// url for the stack
	Url NullableString `json:"url,omitempty"`
}

// NewStackUpdateRequestV1 instantiates a new StackUpdateRequestV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStackUpdateRequestV1() *StackUpdateRequestV1 {
	this := StackUpdateRequestV1{}
	return &this
}

// NewStackUpdateRequestV1WithDefaults instantiates a new StackUpdateRequestV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStackUpdateRequestV1WithDefaults() *StackUpdateRequestV1 {
	this := StackUpdateRequestV1{}
	return &this
}

// GetDeleteProtection returns the DeleteProtection field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StackUpdateRequestV1) GetDeleteProtection() bool {
	if o == nil || IsNil(o.DeleteProtection.Get()) {
		var ret bool
		return ret
	}
	return *o.DeleteProtection.Get()
}

// GetDeleteProtectionOk returns a tuple with the DeleteProtection field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StackUpdateRequestV1) GetDeleteProtectionOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeleteProtection.Get(), o.DeleteProtection.IsSet()
}

// HasDeleteProtection returns a boolean if a field has been set.
func (o *StackUpdateRequestV1) HasDeleteProtection() bool {
	if o != nil && o.DeleteProtection.IsSet() {
		return true
	}

	return false
}

// SetDeleteProtection gets a reference to the given NullableBool and assigns it to the DeleteProtection field.
func (o *StackUpdateRequestV1) SetDeleteProtection(v bool) {
	o.DeleteProtection.Set(&v)
}

// SetDeleteProtectionNil sets the value for DeleteProtection to be an explicit nil
func (o *StackUpdateRequestV1) SetDeleteProtectionNil() {
	o.DeleteProtection.Set(nil)
}

// UnsetDeleteProtection ensures that no value is present for DeleteProtection, not even an explicit nil
func (o *StackUpdateRequestV1) UnsetDeleteProtection() {
	o.DeleteProtection.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StackUpdateRequestV1) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StackUpdateRequestV1) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *StackUpdateRequestV1) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *StackUpdateRequestV1) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *StackUpdateRequestV1) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *StackUpdateRequestV1) UnsetDescription() {
	o.Description.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *StackUpdateRequestV1) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackUpdateRequestV1) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *StackUpdateRequestV1) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *StackUpdateRequestV1) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StackUpdateRequestV1) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StackUpdateRequestV1) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *StackUpdateRequestV1) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *StackUpdateRequestV1) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *StackUpdateRequestV1) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *StackUpdateRequestV1) UnsetName() {
	o.Name.Unset()
}

// GetSlug returns the Slug field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StackUpdateRequestV1) GetSlug() string {
	if o == nil || IsNil(o.Slug.Get()) {
		var ret string
		return ret
	}
	return *o.Slug.Get()
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StackUpdateRequestV1) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Slug.Get(), o.Slug.IsSet()
}

// HasSlug returns a boolean if a field has been set.
func (o *StackUpdateRequestV1) HasSlug() bool {
	if o != nil && o.Slug.IsSet() {
		return true
	}

	return false
}

// SetSlug gets a reference to the given NullableString and assigns it to the Slug field.
func (o *StackUpdateRequestV1) SetSlug(v string) {
	o.Slug.Set(&v)
}

// SetSlugNil sets the value for Slug to be an explicit nil
func (o *StackUpdateRequestV1) SetSlugNil() {
	o.Slug.Set(nil)
}

// UnsetSlug ensures that no value is present for Slug, not even an explicit nil
func (o *StackUpdateRequestV1) UnsetSlug() {
	o.Slug.Unset()
}

// GetUrl returns the Url field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StackUpdateRequestV1) GetUrl() string {
	if o == nil || IsNil(o.Url.Get()) {
		var ret string
		return ret
	}
	return *o.Url.Get()
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StackUpdateRequestV1) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Url.Get(), o.Url.IsSet()
}

// HasUrl returns a boolean if a field has been set.
func (o *StackUpdateRequestV1) HasUrl() bool {
	if o != nil && o.Url.IsSet() {
		return true
	}

	return false
}

// SetUrl gets a reference to the given NullableString and assigns it to the Url field.
func (o *StackUpdateRequestV1) SetUrl(v string) {
	o.Url.Set(&v)
}

// SetUrlNil sets the value for Url to be an explicit nil
func (o *StackUpdateRequestV1) SetUrlNil() {
	o.Url.Set(nil)
}

// UnsetUrl ensures that no value is present for Url, not even an explicit nil
func (o *StackUpdateRequestV1) UnsetUrl() {
	o.Url.Unset()
}

func (o StackUpdateRequestV1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StackUpdateRequestV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DeleteProtection.IsSet() {
		toSerialize["deleteProtection"] = o.DeleteProtection.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Slug.IsSet() {
		toSerialize["slug"] = o.Slug.Get()
	}
	if o.Url.IsSet() {
		toSerialize["url"] = o.Url.Get()
	}
	return toSerialize, nil
}

type NullableStackUpdateRequestV1 struct {
	value *StackUpdateRequestV1
	isSet bool
}

func (v NullableStackUpdateRequestV1) Get() *StackUpdateRequestV1 {
	return v.value
}

func (v *NullableStackUpdateRequestV1) Set(val *StackUpdateRequestV1) {
	v.value = val
	v.isSet = true
}

func (v NullableStackUpdateRequestV1) IsSet() bool {
	return v.isSet
}

func (v *NullableStackUpdateRequestV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStackUpdateRequestV1(val *StackUpdateRequestV1) *NullableStackUpdateRequestV1 {
	return &NullableStackUpdateRequestV1{value: val, isSet: true}
}

func (v NullableStackUpdateRequestV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStackUpdateRequestV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
