/*
GCOM API

Grafana.com API (public).  Looking for GCOM API client packages? You can find them at [grafana-com-public-clients](https://github.com/grafana/grafana-com-public-clients) repository.  If you have any questions, please contact support in the Grafana Cloud UI.  This spec is in *Beta* stage, so use it with caution: - Not all endpoint responses are properly typed for the time being. - Some request parameter types may not be precise

API version: public
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the Next type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Next{}

// Next struct for Next
type Next struct {
	Product              *string        `json:"product,omitempty"`
	Payload              *Payload       `json:"payload,omitempty"`
	Plan                 NullableString `json:"plan,omitempty"`
	PublicName           NullableString `json:"publicName,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Next Next

// NewNext instantiates a new Next object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNext() *Next {
	this := Next{}
	return &this
}

// NewNextWithDefaults instantiates a new Next object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNextWithDefaults() *Next {
	this := Next{}
	return &this
}

// GetProduct returns the Product field value if set, zero value otherwise.
func (o *Next) GetProduct() string {
	if o == nil || IsNil(o.Product) {
		var ret string
		return ret
	}
	return *o.Product
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Next) GetProductOk() (*string, bool) {
	if o == nil || IsNil(o.Product) {
		return nil, false
	}
	return o.Product, true
}

// HasProduct returns a boolean if a field has been set.
func (o *Next) HasProduct() bool {
	if o != nil && !IsNil(o.Product) {
		return true
	}

	return false
}

// SetProduct gets a reference to the given string and assigns it to the Product field.
func (o *Next) SetProduct(v string) {
	o.Product = &v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *Next) GetPayload() Payload {
	if o == nil || IsNil(o.Payload) {
		var ret Payload
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Next) GetPayloadOk() (*Payload, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *Next) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given Payload and assigns it to the Payload field.
func (o *Next) SetPayload(v Payload) {
	o.Payload = &v
}

// GetPlan returns the Plan field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Next) GetPlan() string {
	if o == nil || IsNil(o.Plan.Get()) {
		var ret string
		return ret
	}
	return *o.Plan.Get()
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Next) GetPlanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Plan.Get(), o.Plan.IsSet()
}

// HasPlan returns a boolean if a field has been set.
func (o *Next) HasPlan() bool {
	if o != nil && o.Plan.IsSet() {
		return true
	}

	return false
}

// SetPlan gets a reference to the given NullableString and assigns it to the Plan field.
func (o *Next) SetPlan(v string) {
	o.Plan.Set(&v)
}

// SetPlanNil sets the value for Plan to be an explicit nil
func (o *Next) SetPlanNil() {
	o.Plan.Set(nil)
}

// UnsetPlan ensures that no value is present for Plan, not even an explicit nil
func (o *Next) UnsetPlan() {
	o.Plan.Unset()
}

// GetPublicName returns the PublicName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Next) GetPublicName() string {
	if o == nil || IsNil(o.PublicName.Get()) {
		var ret string
		return ret
	}
	return *o.PublicName.Get()
}

// GetPublicNameOk returns a tuple with the PublicName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Next) GetPublicNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PublicName.Get(), o.PublicName.IsSet()
}

// HasPublicName returns a boolean if a field has been set.
func (o *Next) HasPublicName() bool {
	if o != nil && o.PublicName.IsSet() {
		return true
	}

	return false
}

// SetPublicName gets a reference to the given NullableString and assigns it to the PublicName field.
func (o *Next) SetPublicName(v string) {
	o.PublicName.Set(&v)
}

// SetPublicNameNil sets the value for PublicName to be an explicit nil
func (o *Next) SetPublicNameNil() {
	o.PublicName.Set(nil)
}

// UnsetPublicName ensures that no value is present for PublicName, not even an explicit nil
func (o *Next) UnsetPublicName() {
	o.PublicName.Unset()
}

func (o Next) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Next) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Product) {
		toSerialize["product"] = o.Product
	}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if o.Plan.IsSet() {
		toSerialize["plan"] = o.Plan.Get()
	}
	if o.PublicName.IsSet() {
		toSerialize["publicName"] = o.PublicName.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Next) UnmarshalJSON(data []byte) (err error) {
	varNext := _Next{}

	err = json.Unmarshal(data, &varNext)

	if err != nil {
		return err
	}

	*o = Next(varNext)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "product")
		delete(additionalProperties, "payload")
		delete(additionalProperties, "plan")
		delete(additionalProperties, "publicName")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNext struct {
	value *Next
	isSet bool
}

func (v NullableNext) Get() *Next {
	return v.value
}

func (v *NullableNext) Set(val *Next) {
	v.value = val
	v.isSet = true
}

func (v NullableNext) IsSet() bool {
	return v.isSet
}

func (v *NullableNext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNext(val *Next) *NullableNext {
	return &NullableNext{value: val, isSet: true}
}

func (v NullableNext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
