/*
GCOM API

Grafana.com API (public).  Looking for GCOM API client packages? You can find them at [grafana-com-public-clients](https://github.com/grafana/grafana-com-public-clients) repository.  If you have any questions, please contact support in the Grafana Cloud UI.  This spec is in *Beta* stage, so use it with caution: - Not all endpoint responses are properly typed for the time being. - Some request parameter types may not be precise

API version: public
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the FormattedOrgMembershipMarketplaceSubscription type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FormattedOrgMembershipMarketplaceSubscription{}

// FormattedOrgMembershipMarketplaceSubscription struct for FormattedOrgMembershipMarketplaceSubscription
type FormattedOrgMembershipMarketplaceSubscription struct {
	Provider             string `json:"provider"`
	IsLegacy             bool   `json:"isLegacy"`
	AdditionalProperties map[string]interface{}
}

type _FormattedOrgMembershipMarketplaceSubscription FormattedOrgMembershipMarketplaceSubscription

// NewFormattedOrgMembershipMarketplaceSubscription instantiates a new FormattedOrgMembershipMarketplaceSubscription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFormattedOrgMembershipMarketplaceSubscription(provider string, isLegacy bool) *FormattedOrgMembershipMarketplaceSubscription {
	this := FormattedOrgMembershipMarketplaceSubscription{}
	this.Provider = provider
	this.IsLegacy = isLegacy
	return &this
}

// NewFormattedOrgMembershipMarketplaceSubscriptionWithDefaults instantiates a new FormattedOrgMembershipMarketplaceSubscription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFormattedOrgMembershipMarketplaceSubscriptionWithDefaults() *FormattedOrgMembershipMarketplaceSubscription {
	this := FormattedOrgMembershipMarketplaceSubscription{}
	return &this
}

// GetProvider returns the Provider field value
func (o *FormattedOrgMembershipMarketplaceSubscription) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *FormattedOrgMembershipMarketplaceSubscription) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *FormattedOrgMembershipMarketplaceSubscription) SetProvider(v string) {
	o.Provider = v
}

// GetIsLegacy returns the IsLegacy field value
func (o *FormattedOrgMembershipMarketplaceSubscription) GetIsLegacy() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsLegacy
}

// GetIsLegacyOk returns a tuple with the IsLegacy field value
// and a boolean to check if the value has been set.
func (o *FormattedOrgMembershipMarketplaceSubscription) GetIsLegacyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsLegacy, true
}

// SetIsLegacy sets field value
func (o *FormattedOrgMembershipMarketplaceSubscription) SetIsLegacy(v bool) {
	o.IsLegacy = v
}

func (o FormattedOrgMembershipMarketplaceSubscription) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FormattedOrgMembershipMarketplaceSubscription) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["provider"] = o.Provider
	toSerialize["isLegacy"] = o.IsLegacy

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FormattedOrgMembershipMarketplaceSubscription) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varFormattedOrgMembershipMarketplaceSubscription := _FormattedOrgMembershipMarketplaceSubscription{}

	err = json.Unmarshal(data, &varFormattedOrgMembershipMarketplaceSubscription)

	if err != nil {
		return err
	}

	*o = FormattedOrgMembershipMarketplaceSubscription(varFormattedOrgMembershipMarketplaceSubscription)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "provider")
		delete(additionalProperties, "isLegacy")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFormattedOrgMembershipMarketplaceSubscription struct {
	value *FormattedOrgMembershipMarketplaceSubscription
	isSet bool
}

func (v NullableFormattedOrgMembershipMarketplaceSubscription) Get() *FormattedOrgMembershipMarketplaceSubscription {
	return v.value
}

func (v *NullableFormattedOrgMembershipMarketplaceSubscription) Set(val *FormattedOrgMembershipMarketplaceSubscription) {
	v.value = val
	v.isSet = true
}

func (v NullableFormattedOrgMembershipMarketplaceSubscription) IsSet() bool {
	return v.isSet
}

func (v *NullableFormattedOrgMembershipMarketplaceSubscription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFormattedOrgMembershipMarketplaceSubscription(val *FormattedOrgMembershipMarketplaceSubscription) *NullableFormattedOrgMembershipMarketplaceSubscription {
	return &NullableFormattedOrgMembershipMarketplaceSubscription{value: val, isSet: true}
}

func (v NullableFormattedOrgMembershipMarketplaceSubscription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFormattedOrgMembershipMarketplaceSubscription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
