/*
GCOM API

Grafana.com API (public).  Looking for GCOM API client packages? You can find them at [grafana-com-public-clients](https://github.com/grafana/grafana-com-public-clients) repository.  If you have any questions, please contact support in the Grafana Cloud UI.  This spec is in *Beta* stage, so use it with caution: - Not all endpoint responses are properly typed for the time being. - Some request parameter types may not be precise

API version: public
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"bytes"
	"encoding/json"
)

// checks if the CreateDatasourceRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDatasourceRequestBody{}

// CreateDatasourceRequestBody struct for CreateDatasourceRequestBody
type CreateDatasourceRequestBody struct {
	// datasource access mode
	Access            string  `json:"access"`
	BasicAuth         *int32  `json:"basicAuth,omitempty"`
	BasicAuthPassword *string `json:"basicAuthPassword,omitempty"`
	BasicAuthUser     *string `json:"basicAuthUser,omitempty"`
	Database          *string `json:"database,omitempty"`
	Editable          *int32  `json:"editable,omitempty"`
	// grafana org id
	GrafanaOrgId *int32                 `json:"grafanaOrgId,omitempty"`
	IsDefault    *int32                 `json:"isDefault,omitempty"`
	JsonData     map[string]interface{} `json:"jsonData,omitempty"`
	// datasource name
	Name           string                 `json:"name"`
	Password       *string                `json:"password,omitempty"`
	SecureJsonData map[string]interface{} `json:"secureJsonData,omitempty"`
	// datasource type
	Type            string  `json:"type"`
	Url             *string `json:"url,omitempty"`
	User            *string `json:"user,omitempty"`
	WithCredentials *int32  `json:"withCredentials,omitempty"`
}

type _CreateDatasourceRequestBody CreateDatasourceRequestBody

// NewCreateDatasourceRequestBody instantiates a new CreateDatasourceRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDatasourceRequestBody(access string, name string, type_ string) *CreateDatasourceRequestBody {
	this := CreateDatasourceRequestBody{}
	this.Access = access
	var grafanaOrgId int32 = 1
	this.GrafanaOrgId = &grafanaOrgId
	this.Name = name
	this.Type = type_
	return &this
}

// NewCreateDatasourceRequestBodyWithDefaults instantiates a new CreateDatasourceRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDatasourceRequestBodyWithDefaults() *CreateDatasourceRequestBody {
	this := CreateDatasourceRequestBody{}
	var grafanaOrgId int32 = 1
	this.GrafanaOrgId = &grafanaOrgId
	return &this
}

// GetAccess returns the Access field value
func (o *CreateDatasourceRequestBody) GetAccess() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Access
}

// GetAccessOk returns a tuple with the Access field value
// and a boolean to check if the value has been set.
func (o *CreateDatasourceRequestBody) GetAccessOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Access, true
}

// SetAccess sets field value
func (o *CreateDatasourceRequestBody) SetAccess(v string) {
	o.Access = v
}

// GetBasicAuth returns the BasicAuth field value if set, zero value otherwise.
func (o *CreateDatasourceRequestBody) GetBasicAuth() int32 {
	if o == nil || IsNil(o.BasicAuth) {
		var ret int32
		return ret
	}
	return *o.BasicAuth
}

// GetBasicAuthOk returns a tuple with the BasicAuth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDatasourceRequestBody) GetBasicAuthOk() (*int32, bool) {
	if o == nil || IsNil(o.BasicAuth) {
		return nil, false
	}
	return o.BasicAuth, true
}

// HasBasicAuth returns a boolean if a field has been set.
func (o *CreateDatasourceRequestBody) HasBasicAuth() bool {
	if o != nil && !IsNil(o.BasicAuth) {
		return true
	}

	return false
}

// SetBasicAuth gets a reference to the given int32 and assigns it to the BasicAuth field.
func (o *CreateDatasourceRequestBody) SetBasicAuth(v int32) {
	o.BasicAuth = &v
}

// GetBasicAuthPassword returns the BasicAuthPassword field value if set, zero value otherwise.
func (o *CreateDatasourceRequestBody) GetBasicAuthPassword() string {
	if o == nil || IsNil(o.BasicAuthPassword) {
		var ret string
		return ret
	}
	return *o.BasicAuthPassword
}

// GetBasicAuthPasswordOk returns a tuple with the BasicAuthPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDatasourceRequestBody) GetBasicAuthPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.BasicAuthPassword) {
		return nil, false
	}
	return o.BasicAuthPassword, true
}

// HasBasicAuthPassword returns a boolean if a field has been set.
func (o *CreateDatasourceRequestBody) HasBasicAuthPassword() bool {
	if o != nil && !IsNil(o.BasicAuthPassword) {
		return true
	}

	return false
}

// SetBasicAuthPassword gets a reference to the given string and assigns it to the BasicAuthPassword field.
func (o *CreateDatasourceRequestBody) SetBasicAuthPassword(v string) {
	o.BasicAuthPassword = &v
}

// GetBasicAuthUser returns the BasicAuthUser field value if set, zero value otherwise.
func (o *CreateDatasourceRequestBody) GetBasicAuthUser() string {
	if o == nil || IsNil(o.BasicAuthUser) {
		var ret string
		return ret
	}
	return *o.BasicAuthUser
}

// GetBasicAuthUserOk returns a tuple with the BasicAuthUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDatasourceRequestBody) GetBasicAuthUserOk() (*string, bool) {
	if o == nil || IsNil(o.BasicAuthUser) {
		return nil, false
	}
	return o.BasicAuthUser, true
}

// HasBasicAuthUser returns a boolean if a field has been set.
func (o *CreateDatasourceRequestBody) HasBasicAuthUser() bool {
	if o != nil && !IsNil(o.BasicAuthUser) {
		return true
	}

	return false
}

// SetBasicAuthUser gets a reference to the given string and assigns it to the BasicAuthUser field.
func (o *CreateDatasourceRequestBody) SetBasicAuthUser(v string) {
	o.BasicAuthUser = &v
}

// GetDatabase returns the Database field value if set, zero value otherwise.
func (o *CreateDatasourceRequestBody) GetDatabase() string {
	if o == nil || IsNil(o.Database) {
		var ret string
		return ret
	}
	return *o.Database
}

// GetDatabaseOk returns a tuple with the Database field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDatasourceRequestBody) GetDatabaseOk() (*string, bool) {
	if o == nil || IsNil(o.Database) {
		return nil, false
	}
	return o.Database, true
}

// HasDatabase returns a boolean if a field has been set.
func (o *CreateDatasourceRequestBody) HasDatabase() bool {
	if o != nil && !IsNil(o.Database) {
		return true
	}

	return false
}

// SetDatabase gets a reference to the given string and assigns it to the Database field.
func (o *CreateDatasourceRequestBody) SetDatabase(v string) {
	o.Database = &v
}

// GetEditable returns the Editable field value if set, zero value otherwise.
func (o *CreateDatasourceRequestBody) GetEditable() int32 {
	if o == nil || IsNil(o.Editable) {
		var ret int32
		return ret
	}
	return *o.Editable
}

// GetEditableOk returns a tuple with the Editable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDatasourceRequestBody) GetEditableOk() (*int32, bool) {
	if o == nil || IsNil(o.Editable) {
		return nil, false
	}
	return o.Editable, true
}

// HasEditable returns a boolean if a field has been set.
func (o *CreateDatasourceRequestBody) HasEditable() bool {
	if o != nil && !IsNil(o.Editable) {
		return true
	}

	return false
}

// SetEditable gets a reference to the given int32 and assigns it to the Editable field.
func (o *CreateDatasourceRequestBody) SetEditable(v int32) {
	o.Editable = &v
}

// GetGrafanaOrgId returns the GrafanaOrgId field value if set, zero value otherwise.
func (o *CreateDatasourceRequestBody) GetGrafanaOrgId() int32 {
	if o == nil || IsNil(o.GrafanaOrgId) {
		var ret int32
		return ret
	}
	return *o.GrafanaOrgId
}

// GetGrafanaOrgIdOk returns a tuple with the GrafanaOrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDatasourceRequestBody) GetGrafanaOrgIdOk() (*int32, bool) {
	if o == nil || IsNil(o.GrafanaOrgId) {
		return nil, false
	}
	return o.GrafanaOrgId, true
}

// HasGrafanaOrgId returns a boolean if a field has been set.
func (o *CreateDatasourceRequestBody) HasGrafanaOrgId() bool {
	if o != nil && !IsNil(o.GrafanaOrgId) {
		return true
	}

	return false
}

// SetGrafanaOrgId gets a reference to the given int32 and assigns it to the GrafanaOrgId field.
func (o *CreateDatasourceRequestBody) SetGrafanaOrgId(v int32) {
	o.GrafanaOrgId = &v
}

// GetIsDefault returns the IsDefault field value if set, zero value otherwise.
func (o *CreateDatasourceRequestBody) GetIsDefault() int32 {
	if o == nil || IsNil(o.IsDefault) {
		var ret int32
		return ret
	}
	return *o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDatasourceRequestBody) GetIsDefaultOk() (*int32, bool) {
	if o == nil || IsNil(o.IsDefault) {
		return nil, false
	}
	return o.IsDefault, true
}

// HasIsDefault returns a boolean if a field has been set.
func (o *CreateDatasourceRequestBody) HasIsDefault() bool {
	if o != nil && !IsNil(o.IsDefault) {
		return true
	}

	return false
}

// SetIsDefault gets a reference to the given int32 and assigns it to the IsDefault field.
func (o *CreateDatasourceRequestBody) SetIsDefault(v int32) {
	o.IsDefault = &v
}

// GetJsonData returns the JsonData field value if set, zero value otherwise.
func (o *CreateDatasourceRequestBody) GetJsonData() map[string]interface{} {
	if o == nil || IsNil(o.JsonData) {
		var ret map[string]interface{}
		return ret
	}
	return o.JsonData
}

// GetJsonDataOk returns a tuple with the JsonData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDatasourceRequestBody) GetJsonDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.JsonData) {
		return map[string]interface{}{}, false
	}
	return o.JsonData, true
}

// HasJsonData returns a boolean if a field has been set.
func (o *CreateDatasourceRequestBody) HasJsonData() bool {
	if o != nil && !IsNil(o.JsonData) {
		return true
	}

	return false
}

// SetJsonData gets a reference to the given map[string]interface{} and assigns it to the JsonData field.
func (o *CreateDatasourceRequestBody) SetJsonData(v map[string]interface{}) {
	o.JsonData = v
}

// GetName returns the Name field value
func (o *CreateDatasourceRequestBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateDatasourceRequestBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateDatasourceRequestBody) SetName(v string) {
	o.Name = v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *CreateDatasourceRequestBody) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDatasourceRequestBody) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *CreateDatasourceRequestBody) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *CreateDatasourceRequestBody) SetPassword(v string) {
	o.Password = &v
}

// GetSecureJsonData returns the SecureJsonData field value if set, zero value otherwise.
func (o *CreateDatasourceRequestBody) GetSecureJsonData() map[string]interface{} {
	if o == nil || IsNil(o.SecureJsonData) {
		var ret map[string]interface{}
		return ret
	}
	return o.SecureJsonData
}

// GetSecureJsonDataOk returns a tuple with the SecureJsonData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDatasourceRequestBody) GetSecureJsonDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.SecureJsonData) {
		return map[string]interface{}{}, false
	}
	return o.SecureJsonData, true
}

// HasSecureJsonData returns a boolean if a field has been set.
func (o *CreateDatasourceRequestBody) HasSecureJsonData() bool {
	if o != nil && !IsNil(o.SecureJsonData) {
		return true
	}

	return false
}

// SetSecureJsonData gets a reference to the given map[string]interface{} and assigns it to the SecureJsonData field.
func (o *CreateDatasourceRequestBody) SetSecureJsonData(v map[string]interface{}) {
	o.SecureJsonData = v
}

// GetType returns the Type field value
func (o *CreateDatasourceRequestBody) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateDatasourceRequestBody) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateDatasourceRequestBody) SetType(v string) {
	o.Type = v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *CreateDatasourceRequestBody) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDatasourceRequestBody) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *CreateDatasourceRequestBody) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *CreateDatasourceRequestBody) SetUrl(v string) {
	o.Url = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *CreateDatasourceRequestBody) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDatasourceRequestBody) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *CreateDatasourceRequestBody) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *CreateDatasourceRequestBody) SetUser(v string) {
	o.User = &v
}

// GetWithCredentials returns the WithCredentials field value if set, zero value otherwise.
func (o *CreateDatasourceRequestBody) GetWithCredentials() int32 {
	if o == nil || IsNil(o.WithCredentials) {
		var ret int32
		return ret
	}
	return *o.WithCredentials
}

// GetWithCredentialsOk returns a tuple with the WithCredentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDatasourceRequestBody) GetWithCredentialsOk() (*int32, bool) {
	if o == nil || IsNil(o.WithCredentials) {
		return nil, false
	}
	return o.WithCredentials, true
}

// HasWithCredentials returns a boolean if a field has been set.
func (o *CreateDatasourceRequestBody) HasWithCredentials() bool {
	if o != nil && !IsNil(o.WithCredentials) {
		return true
	}

	return false
}

// SetWithCredentials gets a reference to the given int32 and assigns it to the WithCredentials field.
func (o *CreateDatasourceRequestBody) SetWithCredentials(v int32) {
	o.WithCredentials = &v
}

func (o CreateDatasourceRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDatasourceRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access"] = o.Access
	if !IsNil(o.BasicAuth) {
		toSerialize["basicAuth"] = o.BasicAuth
	}
	if !IsNil(o.BasicAuthPassword) {
		toSerialize["basicAuthPassword"] = o.BasicAuthPassword
	}
	if !IsNil(o.BasicAuthUser) {
		toSerialize["basicAuthUser"] = o.BasicAuthUser
	}
	if !IsNil(o.Database) {
		toSerialize["database"] = o.Database
	}
	if !IsNil(o.Editable) {
		toSerialize["editable"] = o.Editable
	}
	if !IsNil(o.GrafanaOrgId) {
		toSerialize["grafanaOrgId"] = o.GrafanaOrgId
	}
	if !IsNil(o.IsDefault) {
		toSerialize["isDefault"] = o.IsDefault
	}
	if !IsNil(o.JsonData) {
		toSerialize["jsonData"] = o.JsonData
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.SecureJsonData) {
		toSerialize["secureJsonData"] = o.SecureJsonData
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.WithCredentials) {
		toSerialize["withCredentials"] = o.WithCredentials
	}
	return toSerialize, nil
}

func (o *CreateDatasourceRequestBody) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varCreateDatasourceRequestBody := _CreateDatasourceRequestBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varCreateDatasourceRequestBody)

	if err != nil {
		return err
	}

	*o = CreateDatasourceRequestBody(varCreateDatasourceRequestBody)

	return err
}

type NullableCreateDatasourceRequestBody struct {
	value *CreateDatasourceRequestBody
	isSet bool
}

func (v NullableCreateDatasourceRequestBody) Get() *CreateDatasourceRequestBody {
	return v.value
}

func (v *NullableCreateDatasourceRequestBody) Set(val *CreateDatasourceRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDatasourceRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDatasourceRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDatasourceRequestBody(val *CreateDatasourceRequestBody) *NullableCreateDatasourceRequestBody {
	return &NullableCreateDatasourceRequestBody{value: val, isSet: true}
}

func (v NullableCreateDatasourceRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDatasourceRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
