/*
GCOM API

Grafana.com API (public).  Looking for GCOM API client packages? You can find them at [grafana-com-public-clients](https://github.com/grafana/grafana-com-public-clients) repository.  If you have any questions, please contact support in the Grafana Cloud UI.  This spec is in *Beta* stage, so use it with caution: - Not all endpoint responses are properly typed for the time being. - Some request parameter types may not be precise

API version: public
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the TokenAuth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenAuth{}

// TokenAuth For data source plugins. Token authentication section used with an OAuth API.
type TokenAuth struct {
	// URL to fetch the authentication token.
	Url *string `json:"url,omitempty"`
	// The list of scopes that your application should be granted access to.
	Scopes               []string `json:"scopes,omitempty"`
	Params               *Params  `json:"params,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TokenAuth TokenAuth

// NewTokenAuth instantiates a new TokenAuth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenAuth() *TokenAuth {
	this := TokenAuth{}
	return &this
}

// NewTokenAuthWithDefaults instantiates a new TokenAuth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenAuthWithDefaults() *TokenAuth {
	this := TokenAuth{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *TokenAuth) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenAuth) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *TokenAuth) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *TokenAuth) SetUrl(v string) {
	o.Url = &v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *TokenAuth) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenAuth) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *TokenAuth) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *TokenAuth) SetScopes(v []string) {
	o.Scopes = v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *TokenAuth) GetParams() Params {
	if o == nil || IsNil(o.Params) {
		var ret Params
		return ret
	}
	return *o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenAuth) GetParamsOk() (*Params, bool) {
	if o == nil || IsNil(o.Params) {
		return nil, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *TokenAuth) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given Params and assigns it to the Params field.
func (o *TokenAuth) SetParams(v Params) {
	o.Params = &v
}

func (o TokenAuth) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenAuth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TokenAuth) UnmarshalJSON(data []byte) (err error) {
	varTokenAuth := _TokenAuth{}

	err = json.Unmarshal(data, &varTokenAuth)

	if err != nil {
		return err
	}

	*o = TokenAuth(varTokenAuth)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "url")
		delete(additionalProperties, "scopes")
		delete(additionalProperties, "params")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTokenAuth struct {
	value *TokenAuth
	isSet bool
}

func (v NullableTokenAuth) Get() *TokenAuth {
	return v.value
}

func (v *NullableTokenAuth) Set(val *TokenAuth) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenAuth) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenAuth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenAuth(val *TokenAuth) *NullableTokenAuth {
	return &NullableTokenAuth{value: val, isSet: true}
}

func (v NullableTokenAuth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenAuth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
