/*
GCOM API

Grafana.com API (public).  Looking for GCOM API client packages? You can find them at [grafana-com-public-clients](https://github.com/grafana/grafana-com-public-clients) repository.  If you have any questions, please contact support in the Grafana Cloud UI.  This spec is in *Beta* stage, so use it with caution: - Not all endpoint responses are properly typed for the time being. - Some request parameter types may not be precise

API version: public
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the RealmsInnerAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RealmsInnerAnyOf{}

// RealmsInnerAnyOf struct for RealmsInnerAnyOf
type RealmsInnerAnyOf struct {
	Type                 string `json:"type"`
	Identifier           string `json:"identifier"`
	AdditionalProperties map[string]interface{}
}

type _RealmsInnerAnyOf RealmsInnerAnyOf

// NewRealmsInnerAnyOf instantiates a new RealmsInnerAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRealmsInnerAnyOf(type_ string, identifier string) *RealmsInnerAnyOf {
	this := RealmsInnerAnyOf{}
	this.Type = type_
	this.Identifier = identifier
	return &this
}

// NewRealmsInnerAnyOfWithDefaults instantiates a new RealmsInnerAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRealmsInnerAnyOfWithDefaults() *RealmsInnerAnyOf {
	this := RealmsInnerAnyOf{}
	return &this
}

// GetType returns the Type field value
func (o *RealmsInnerAnyOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RealmsInnerAnyOf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RealmsInnerAnyOf) SetType(v string) {
	o.Type = v
}

// GetIdentifier returns the Identifier field value
func (o *RealmsInnerAnyOf) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *RealmsInnerAnyOf) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *RealmsInnerAnyOf) SetIdentifier(v string) {
	o.Identifier = v
}

func (o RealmsInnerAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RealmsInnerAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["identifier"] = o.Identifier

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RealmsInnerAnyOf) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varRealmsInnerAnyOf := _RealmsInnerAnyOf{}

	err = json.Unmarshal(data, &varRealmsInnerAnyOf)

	if err != nil {
		return err
	}

	*o = RealmsInnerAnyOf(varRealmsInnerAnyOf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "identifier")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRealmsInnerAnyOf struct {
	value *RealmsInnerAnyOf
	isSet bool
}

func (v NullableRealmsInnerAnyOf) Get() *RealmsInnerAnyOf {
	return v.value
}

func (v *NullableRealmsInnerAnyOf) Set(val *RealmsInnerAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableRealmsInnerAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableRealmsInnerAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRealmsInnerAnyOf(val *RealmsInnerAnyOf) *NullableRealmsInnerAnyOf {
	return &NullableRealmsInnerAnyOf{value: val, isSet: true}
}

func (v NullableRealmsInnerAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRealmsInnerAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
