/*
GCOM API

Grafana.com API (public).  Looking for GCOM API client packages? You can find them at [grafana-com-public-clients](https://github.com/grafana/grafana-com-public-clients) repository.  If you have any questions, please contact support in the Grafana Cloud UI.  This spec is in *Beta* stage, so use it with caution: - Not all endpoint responses are properly typed for the time being. - Some request parameter types may not be precise

API version: public
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"bytes"
	"encoding/json"
	"time"
)

// checks if the FormattedApiInstanceDashboard type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FormattedApiInstanceDashboard{}

// FormattedApiInstanceDashboard struct for FormattedApiInstanceDashboard
type FormattedApiInstanceDashboard struct {
	// when the dashboard was created
	CreatedAt time.Time `json:"createdAt"`
	// the dashboard definition
	DashboardJson interface{} `json:"dashboardJson"`
	// whether the dashboard is protected from deletion
	DisableDelete bool `json:"disableDelete"`
	// dashboard folder
	Folder string `json:"folder"`
	// grafana org id
	GrafanaOrgId int32 `json:"grafanaOrgId"`
	// dashboard id
	Id int64 `json:"id"`
	// hosted grafana instance id
	InstanceId int32 `json:"instanceId"`
	// dashboard name
	Name string `json:"name"`
	// when the dashboard was last updated
	UpdatedAt NullableTime `json:"updatedAt"`
}

type _FormattedApiInstanceDashboard FormattedApiInstanceDashboard

// NewFormattedApiInstanceDashboard instantiates a new FormattedApiInstanceDashboard object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFormattedApiInstanceDashboard(createdAt time.Time, dashboardJson interface{}, disableDelete bool, folder string, grafanaOrgId int32, id int64, instanceId int32, name string, updatedAt NullableTime) *FormattedApiInstanceDashboard {
	this := FormattedApiInstanceDashboard{}
	this.CreatedAt = createdAt
	this.DashboardJson = dashboardJson
	this.DisableDelete = disableDelete
	this.Folder = folder
	this.GrafanaOrgId = grafanaOrgId
	this.Id = id
	this.InstanceId = instanceId
	this.Name = name
	this.UpdatedAt = updatedAt
	return &this
}

// NewFormattedApiInstanceDashboardWithDefaults instantiates a new FormattedApiInstanceDashboard object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFormattedApiInstanceDashboardWithDefaults() *FormattedApiInstanceDashboard {
	this := FormattedApiInstanceDashboard{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *FormattedApiInstanceDashboard) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *FormattedApiInstanceDashboard) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *FormattedApiInstanceDashboard) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetDashboardJson returns the DashboardJson field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *FormattedApiInstanceDashboard) GetDashboardJson() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.DashboardJson
}

// GetDashboardJsonOk returns a tuple with the DashboardJson field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FormattedApiInstanceDashboard) GetDashboardJsonOk() (*interface{}, bool) {
	if o == nil || IsNil(o.DashboardJson) {
		return nil, false
	}
	return &o.DashboardJson, true
}

// SetDashboardJson sets field value
func (o *FormattedApiInstanceDashboard) SetDashboardJson(v interface{}) {
	o.DashboardJson = v
}

// GetDisableDelete returns the DisableDelete field value
func (o *FormattedApiInstanceDashboard) GetDisableDelete() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DisableDelete
}

// GetDisableDeleteOk returns a tuple with the DisableDelete field value
// and a boolean to check if the value has been set.
func (o *FormattedApiInstanceDashboard) GetDisableDeleteOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisableDelete, true
}

// SetDisableDelete sets field value
func (o *FormattedApiInstanceDashboard) SetDisableDelete(v bool) {
	o.DisableDelete = v
}

// GetFolder returns the Folder field value
func (o *FormattedApiInstanceDashboard) GetFolder() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Folder
}

// GetFolderOk returns a tuple with the Folder field value
// and a boolean to check if the value has been set.
func (o *FormattedApiInstanceDashboard) GetFolderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Folder, true
}

// SetFolder sets field value
func (o *FormattedApiInstanceDashboard) SetFolder(v string) {
	o.Folder = v
}

// GetGrafanaOrgId returns the GrafanaOrgId field value
func (o *FormattedApiInstanceDashboard) GetGrafanaOrgId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GrafanaOrgId
}

// GetGrafanaOrgIdOk returns a tuple with the GrafanaOrgId field value
// and a boolean to check if the value has been set.
func (o *FormattedApiInstanceDashboard) GetGrafanaOrgIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrafanaOrgId, true
}

// SetGrafanaOrgId sets field value
func (o *FormattedApiInstanceDashboard) SetGrafanaOrgId(v int32) {
	o.GrafanaOrgId = v
}

// GetId returns the Id field value
func (o *FormattedApiInstanceDashboard) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FormattedApiInstanceDashboard) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FormattedApiInstanceDashboard) SetId(v int64) {
	o.Id = v
}

// GetInstanceId returns the InstanceId field value
func (o *FormattedApiInstanceDashboard) GetInstanceId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value
// and a boolean to check if the value has been set.
func (o *FormattedApiInstanceDashboard) GetInstanceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceId, true
}

// SetInstanceId sets field value
func (o *FormattedApiInstanceDashboard) SetInstanceId(v int32) {
	o.InstanceId = v
}

// GetName returns the Name field value
func (o *FormattedApiInstanceDashboard) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FormattedApiInstanceDashboard) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FormattedApiInstanceDashboard) SetName(v string) {
	o.Name = v
}

// GetUpdatedAt returns the UpdatedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *FormattedApiInstanceDashboard) GetUpdatedAt() time.Time {
	if o == nil || o.UpdatedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FormattedApiInstanceDashboard) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// SetUpdatedAt sets field value
func (o *FormattedApiInstanceDashboard) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}

func (o FormattedApiInstanceDashboard) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FormattedApiInstanceDashboard) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["createdAt"] = o.CreatedAt
	if o.DashboardJson != nil {
		toSerialize["dashboardJson"] = o.DashboardJson
	}
	toSerialize["disableDelete"] = o.DisableDelete
	toSerialize["folder"] = o.Folder
	toSerialize["grafanaOrgId"] = o.GrafanaOrgId
	toSerialize["id"] = o.Id
	toSerialize["instanceId"] = o.InstanceId
	toSerialize["name"] = o.Name
	toSerialize["updatedAt"] = o.UpdatedAt.Get()
	return toSerialize, nil
}

func (o *FormattedApiInstanceDashboard) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varFormattedApiInstanceDashboard := _FormattedApiInstanceDashboard{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varFormattedApiInstanceDashboard)

	if err != nil {
		return err
	}

	*o = FormattedApiInstanceDashboard(varFormattedApiInstanceDashboard)

	return err
}

type NullableFormattedApiInstanceDashboard struct {
	value *FormattedApiInstanceDashboard
	isSet bool
}

func (v NullableFormattedApiInstanceDashboard) Get() *FormattedApiInstanceDashboard {
	return v.value
}

func (v *NullableFormattedApiInstanceDashboard) Set(val *FormattedApiInstanceDashboard) {
	v.value = val
	v.isSet = true
}

func (v NullableFormattedApiInstanceDashboard) IsSet() bool {
	return v.isSet
}

func (v *NullableFormattedApiInstanceDashboard) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFormattedApiInstanceDashboard(val *FormattedApiInstanceDashboard) *NullableFormattedApiInstanceDashboard {
	return &NullableFormattedApiInstanceDashboard{value: val, isSet: true}
}

func (v NullableFormattedApiInstanceDashboard) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFormattedApiInstanceDashboard) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
