/*
GCOM API

 Grafana.com API (or GCOM). This documentation includes all endpoints of GCOM API including the staff ones.  Looking for GCOM API client packages? You can find them at [grafana-com-clients](https://github.com/grafana/grafana-com-clients) repository.  If you have any questions, please contact us at #grafana_com on Slack or open an issue at [Grafana-com repository](https://github.com/grafana/grafana-com/issues/new).  This spec is in *Beta* stage, so use it with caution: - Not all endpoint responses are properly typed for the time being. - Some request parameter types may not be precise       

API version: internal
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostInstanceServiceAccountTokensRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostInstanceServiceAccountTokensRequest{}

// PostInstanceServiceAccountTokensRequest struct for PostInstanceServiceAccountTokensRequest
type PostInstanceServiceAccountTokensRequest struct {
	Name string `json:"name"`
	SecondsToLive *int32 `json:"secondsToLive,omitempty"`
}

type _PostInstanceServiceAccountTokensRequest PostInstanceServiceAccountTokensRequest

// NewPostInstanceServiceAccountTokensRequest instantiates a new PostInstanceServiceAccountTokensRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostInstanceServiceAccountTokensRequest(name string) *PostInstanceServiceAccountTokensRequest {
	this := PostInstanceServiceAccountTokensRequest{}
	this.Name = name
	return &this
}

// NewPostInstanceServiceAccountTokensRequestWithDefaults instantiates a new PostInstanceServiceAccountTokensRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostInstanceServiceAccountTokensRequestWithDefaults() *PostInstanceServiceAccountTokensRequest {
	this := PostInstanceServiceAccountTokensRequest{}
	return &this
}

// GetName returns the Name field value
func (o *PostInstanceServiceAccountTokensRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PostInstanceServiceAccountTokensRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PostInstanceServiceAccountTokensRequest) SetName(v string) {
	o.Name = v
}

// GetSecondsToLive returns the SecondsToLive field value if set, zero value otherwise.
func (o *PostInstanceServiceAccountTokensRequest) GetSecondsToLive() int32 {
	if o == nil || IsNil(o.SecondsToLive) {
		var ret int32
		return ret
	}
	return *o.SecondsToLive
}

// GetSecondsToLiveOk returns a tuple with the SecondsToLive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostInstanceServiceAccountTokensRequest) GetSecondsToLiveOk() (*int32, bool) {
	if o == nil || IsNil(o.SecondsToLive) {
		return nil, false
	}
	return o.SecondsToLive, true
}

// HasSecondsToLive returns a boolean if a field has been set.
func (o *PostInstanceServiceAccountTokensRequest) HasSecondsToLive() bool {
	if o != nil && !IsNil(o.SecondsToLive) {
		return true
	}

	return false
}

// SetSecondsToLive gets a reference to the given int32 and assigns it to the SecondsToLive field.
func (o *PostInstanceServiceAccountTokensRequest) SetSecondsToLive(v int32) {
	o.SecondsToLive = &v
}

func (o PostInstanceServiceAccountTokensRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostInstanceServiceAccountTokensRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.SecondsToLive) {
		toSerialize["secondsToLive"] = o.SecondsToLive
	}
	return toSerialize, nil
}

func (o *PostInstanceServiceAccountTokensRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostInstanceServiceAccountTokensRequest := _PostInstanceServiceAccountTokensRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostInstanceServiceAccountTokensRequest)

	if err != nil {
		return err
	}

	*o = PostInstanceServiceAccountTokensRequest(varPostInstanceServiceAccountTokensRequest)

	return err
}

type NullablePostInstanceServiceAccountTokensRequest struct {
	value *PostInstanceServiceAccountTokensRequest
	isSet bool
}

func (v NullablePostInstanceServiceAccountTokensRequest) Get() *PostInstanceServiceAccountTokensRequest {
	return v.value
}

func (v *NullablePostInstanceServiceAccountTokensRequest) Set(val *PostInstanceServiceAccountTokensRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostInstanceServiceAccountTokensRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostInstanceServiceAccountTokensRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostInstanceServiceAccountTokensRequest(val *PostInstanceServiceAccountTokensRequest) *NullablePostInstanceServiceAccountTokensRequest {
	return &NullablePostInstanceServiceAccountTokensRequest{value: val, isSet: true}
}

func (v NullablePostInstanceServiceAccountTokensRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostInstanceServiceAccountTokensRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


