/*
GCOM API

Grafana.com API (public).  Looking for GCOM API client packages? You can find them at [grafana-com-public-clients](https://github.com/grafana/grafana-com-public-clients) repository.  If you have any questions, please contact support in the Grafana Cloud UI.  This spec is in *Beta* stage, so use it with caution: - Not all endpoint responses are properly typed for the time being. - Some request parameter types may not be precise

API version: public
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
	"fmt"
)

// Mimir struct for Mimir
type Mimir struct {
	ApiAnyOf  *ApiAnyOf
	ApiAnyOf1 *ApiAnyOf1
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Mimir) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ApiAnyOf
	err = json.Unmarshal(data, &dst.ApiAnyOf)
	if err == nil {
		jsonApiAnyOf, _ := json.Marshal(dst.ApiAnyOf)
		if string(jsonApiAnyOf) == "{}" { // empty struct
			dst.ApiAnyOf = nil
		} else {
			return nil // data stored in dst.ApiAnyOf, return on the first match
		}
	} else {
		dst.ApiAnyOf = nil
	}

	// try to unmarshal JSON data into ApiAnyOf1
	err = json.Unmarshal(data, &dst.ApiAnyOf1)
	if err == nil {
		jsonApiAnyOf1, _ := json.Marshal(dst.ApiAnyOf1)
		if string(jsonApiAnyOf1) == "{}" { // empty struct
			dst.ApiAnyOf1 = nil
		} else {
			return nil // data stored in dst.ApiAnyOf1, return on the first match
		}
	} else {
		dst.ApiAnyOf1 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Mimir)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *Mimir) MarshalJSON() ([]byte, error) {
	if src.ApiAnyOf != nil {
		return json.Marshal(&src.ApiAnyOf)
	}

	if src.ApiAnyOf1 != nil {
		return json.Marshal(&src.ApiAnyOf1)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableMimir struct {
	value *Mimir
	isSet bool
}

func (v NullableMimir) Get() *Mimir {
	return v.value
}

func (v *NullableMimir) Set(val *Mimir) {
	v.value = val
	v.isSet = true
}

func (v NullableMimir) IsSet() bool {
	return v.isSet
}

func (v *NullableMimir) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMimir(val *Mimir) *NullableMimir {
	return &NullableMimir{value: val, isSet: true}
}

func (v NullableMimir) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMimir) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
