/*
GCOM API

Grafana.com API (public).  Looking for GCOM API client packages? You can find them at [grafana-com-public-clients](https://github.com/grafana/grafana-com-public-clients) repository.  If you have any questions, please contact support in the Grafana Cloud UI.  This spec is in *Beta* stage, so use it with caution: - Not all endpoint responses are properly typed for the time being. - Some request parameter types may not be precise

API version: public
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the JwtTokenAuth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JwtTokenAuth{}

// JwtTokenAuth For data source plugins. Token authentication section used with an JWT OAuth API.
type JwtTokenAuth struct {
	// URL to fetch the JWT token.
	Url *string `json:"url,omitempty"`
	// The list of scopes that your application should be granted access to.
	Scopes               []string `json:"scopes,omitempty"`
	Params               *Params1 `json:"params,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _JwtTokenAuth JwtTokenAuth

// NewJwtTokenAuth instantiates a new JwtTokenAuth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJwtTokenAuth() *JwtTokenAuth {
	this := JwtTokenAuth{}
	return &this
}

// NewJwtTokenAuthWithDefaults instantiates a new JwtTokenAuth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJwtTokenAuthWithDefaults() *JwtTokenAuth {
	this := JwtTokenAuth{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *JwtTokenAuth) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JwtTokenAuth) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *JwtTokenAuth) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *JwtTokenAuth) SetUrl(v string) {
	o.Url = &v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *JwtTokenAuth) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JwtTokenAuth) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *JwtTokenAuth) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *JwtTokenAuth) SetScopes(v []string) {
	o.Scopes = v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *JwtTokenAuth) GetParams() Params1 {
	if o == nil || IsNil(o.Params) {
		var ret Params1
		return ret
	}
	return *o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JwtTokenAuth) GetParamsOk() (*Params1, bool) {
	if o == nil || IsNil(o.Params) {
		return nil, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *JwtTokenAuth) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given Params1 and assigns it to the Params field.
func (o *JwtTokenAuth) SetParams(v Params1) {
	o.Params = &v
}

func (o JwtTokenAuth) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JwtTokenAuth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *JwtTokenAuth) UnmarshalJSON(data []byte) (err error) {
	varJwtTokenAuth := _JwtTokenAuth{}

	err = json.Unmarshal(data, &varJwtTokenAuth)

	if err != nil {
		return err
	}

	*o = JwtTokenAuth(varJwtTokenAuth)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "url")
		delete(additionalProperties, "scopes")
		delete(additionalProperties, "params")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJwtTokenAuth struct {
	value *JwtTokenAuth
	isSet bool
}

func (v NullableJwtTokenAuth) Get() *JwtTokenAuth {
	return v.value
}

func (v *NullableJwtTokenAuth) Set(val *JwtTokenAuth) {
	v.value = val
	v.isSet = true
}

func (v NullableJwtTokenAuth) IsSet() bool {
	return v.isSet
}

func (v *NullableJwtTokenAuth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJwtTokenAuth(val *JwtTokenAuth) *NullableJwtTokenAuth {
	return &NullableJwtTokenAuth{value: val, isSet: true}
}

func (v NullableJwtTokenAuth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJwtTokenAuth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
