/*
GCOM API

Grafana.com API (public).  Looking for GCOM API client packages? You can find them at [grafana-com-public-clients](https://github.com/grafana/grafana-com-public-clients) repository.  If you have any questions, please contact support in the Grafana Cloud UI.  This spec is in *Beta* stage, so use it with caution: - Not all endpoint responses are properly typed for the time being. - Some request parameter types may not be precise

API version: public
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the StackConnectionServicesV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StackConnectionServicesV1{}

// StackConnectionServicesV1 struct for StackConnectionServicesV1
type StackConnectionServicesV1 struct {
	InfluxUrl                 *string `json:"influxUrl,omitempty"`
	OncallApiUrl              *string `json:"oncallApiUrl,omitempty"`
	SyntheticMonitoringApiUrl *string `json:"syntheticMonitoringApiUrl,omitempty"`
}

// NewStackConnectionServicesV1 instantiates a new StackConnectionServicesV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStackConnectionServicesV1() *StackConnectionServicesV1 {
	this := StackConnectionServicesV1{}
	return &this
}

// NewStackConnectionServicesV1WithDefaults instantiates a new StackConnectionServicesV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStackConnectionServicesV1WithDefaults() *StackConnectionServicesV1 {
	this := StackConnectionServicesV1{}
	return &this
}

// GetInfluxUrl returns the InfluxUrl field value if set, zero value otherwise.
func (o *StackConnectionServicesV1) GetInfluxUrl() string {
	if o == nil || IsNil(o.InfluxUrl) {
		var ret string
		return ret
	}
	return *o.InfluxUrl
}

// GetInfluxUrlOk returns a tuple with the InfluxUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackConnectionServicesV1) GetInfluxUrlOk() (*string, bool) {
	if o == nil || IsNil(o.InfluxUrl) {
		return nil, false
	}
	return o.InfluxUrl, true
}

// HasInfluxUrl returns a boolean if a field has been set.
func (o *StackConnectionServicesV1) HasInfluxUrl() bool {
	if o != nil && !IsNil(o.InfluxUrl) {
		return true
	}

	return false
}

// SetInfluxUrl gets a reference to the given string and assigns it to the InfluxUrl field.
func (o *StackConnectionServicesV1) SetInfluxUrl(v string) {
	o.InfluxUrl = &v
}

// GetOncallApiUrl returns the OncallApiUrl field value if set, zero value otherwise.
func (o *StackConnectionServicesV1) GetOncallApiUrl() string {
	if o == nil || IsNil(o.OncallApiUrl) {
		var ret string
		return ret
	}
	return *o.OncallApiUrl
}

// GetOncallApiUrlOk returns a tuple with the OncallApiUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackConnectionServicesV1) GetOncallApiUrlOk() (*string, bool) {
	if o == nil || IsNil(o.OncallApiUrl) {
		return nil, false
	}
	return o.OncallApiUrl, true
}

// HasOncallApiUrl returns a boolean if a field has been set.
func (o *StackConnectionServicesV1) HasOncallApiUrl() bool {
	if o != nil && !IsNil(o.OncallApiUrl) {
		return true
	}

	return false
}

// SetOncallApiUrl gets a reference to the given string and assigns it to the OncallApiUrl field.
func (o *StackConnectionServicesV1) SetOncallApiUrl(v string) {
	o.OncallApiUrl = &v
}

// GetSyntheticMonitoringApiUrl returns the SyntheticMonitoringApiUrl field value if set, zero value otherwise.
func (o *StackConnectionServicesV1) GetSyntheticMonitoringApiUrl() string {
	if o == nil || IsNil(o.SyntheticMonitoringApiUrl) {
		var ret string
		return ret
	}
	return *o.SyntheticMonitoringApiUrl
}

// GetSyntheticMonitoringApiUrlOk returns a tuple with the SyntheticMonitoringApiUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackConnectionServicesV1) GetSyntheticMonitoringApiUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SyntheticMonitoringApiUrl) {
		return nil, false
	}
	return o.SyntheticMonitoringApiUrl, true
}

// HasSyntheticMonitoringApiUrl returns a boolean if a field has been set.
func (o *StackConnectionServicesV1) HasSyntheticMonitoringApiUrl() bool {
	if o != nil && !IsNil(o.SyntheticMonitoringApiUrl) {
		return true
	}

	return false
}

// SetSyntheticMonitoringApiUrl gets a reference to the given string and assigns it to the SyntheticMonitoringApiUrl field.
func (o *StackConnectionServicesV1) SetSyntheticMonitoringApiUrl(v string) {
	o.SyntheticMonitoringApiUrl = &v
}

func (o StackConnectionServicesV1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StackConnectionServicesV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InfluxUrl) {
		toSerialize["influxUrl"] = o.InfluxUrl
	}
	if !IsNil(o.OncallApiUrl) {
		toSerialize["oncallApiUrl"] = o.OncallApiUrl
	}
	if !IsNil(o.SyntheticMonitoringApiUrl) {
		toSerialize["syntheticMonitoringApiUrl"] = o.SyntheticMonitoringApiUrl
	}
	return toSerialize, nil
}

type NullableStackConnectionServicesV1 struct {
	value *StackConnectionServicesV1
	isSet bool
}

func (v NullableStackConnectionServicesV1) Get() *StackConnectionServicesV1 {
	return v.value
}

func (v *NullableStackConnectionServicesV1) Set(val *StackConnectionServicesV1) {
	v.value = val
	v.isSet = true
}

func (v NullableStackConnectionServicesV1) IsSet() bool {
	return v.isSet
}

func (v *NullableStackConnectionServicesV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStackConnectionServicesV1(val *StackConnectionServicesV1) *NullableStackConnectionServicesV1 {
	return &NullableStackConnectionServicesV1{value: val, isSet: true}
}

func (v NullableStackConnectionServicesV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStackConnectionServicesV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
