/*
GCOM API

Grafana.com API (public).  Looking for GCOM API client packages? You can find them at [grafana-com-public-clients](https://github.com/grafana/grafana-com-public-clients) repository.  If you have any questions, please contact support in the Grafana Cloud UI.  This spec is in *Beta* stage, so use it with caution: - Not all endpoint responses are properly typed for the time being. - Some request parameter types may not be precise

API version: public
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the ServiceAccountsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceAccountsInner{}

// ServiceAccountsInner struct for ServiceAccountsInner
type ServiceAccountsInner struct {
	Id                   float32 `json:"id"`
	Name                 string  `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _ServiceAccountsInner ServiceAccountsInner

// NewServiceAccountsInner instantiates a new ServiceAccountsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceAccountsInner(id float32, name string) *ServiceAccountsInner {
	this := ServiceAccountsInner{}
	this.Id = id
	this.Name = name
	return &this
}

// NewServiceAccountsInnerWithDefaults instantiates a new ServiceAccountsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceAccountsInnerWithDefaults() *ServiceAccountsInner {
	this := ServiceAccountsInner{}
	return &this
}

// GetId returns the Id field value
func (o *ServiceAccountsInner) GetId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ServiceAccountsInner) GetIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ServiceAccountsInner) SetId(v float32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ServiceAccountsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServiceAccountsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServiceAccountsInner) SetName(v string) {
	o.Name = v
}

func (o ServiceAccountsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceAccountsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServiceAccountsInner) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varServiceAccountsInner := _ServiceAccountsInner{}

	err = json.Unmarshal(data, &varServiceAccountsInner)

	if err != nil {
		return err
	}

	*o = ServiceAccountsInner(varServiceAccountsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServiceAccountsInner struct {
	value *ServiceAccountsInner
	isSet bool
}

func (v NullableServiceAccountsInner) Get() *ServiceAccountsInner {
	return v.value
}

func (v *NullableServiceAccountsInner) Set(val *ServiceAccountsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceAccountsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceAccountsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceAccountsInner(val *ServiceAccountsInner) *NullableServiceAccountsInner {
	return &NullableServiceAccountsInner{value: val, isSet: true}
}

func (v NullableServiceAccountsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceAccountsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
