/*
GCOM API

Grafana.com API (public).  Looking for GCOM API client packages? You can find them at [grafana-com-public-clients](https://github.com/grafana/grafana-com-public-clients) repository.  If you have any questions, please contact support in the Grafana Cloud UI.  This spec is in *Beta* stage, so use it with caution: - Not all endpoint responses are properly typed for the time being. - Some request parameter types may not be precise.

API version: public
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"bytes"
	"encoding/json"
	"time"
)

// checks if the InternalStackCreateRequestV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternalStackCreateRequestV1{}

// InternalStackCreateRequestV1 struct for InternalStackCreateRequestV1
type InternalStackCreateRequestV1 struct {
	// protection active or not for the stack
	DeleteProtection *bool `json:"deleteProtection,omitempty"`
	// description of the stack
	Description NullableString `json:"description,omitempty"`
	// labels to add to the stack
	Labels *map[string]string `json:"labels,omitempty"`
	// of the stack
	Name string `json:"name"`
	// org owning the stack
	Org string `json:"org"`
	// plugins to install to the stack
	Plugins []string `json:"plugins,omitempty"`
	// region of the stack
	Region string `json:"region"`
	// slug of the stack
	Slug string `json:"slug"`
	// trial expiration date for the stack
	TrialExpiresAt NullableTime `json:"trialExpiresAt,omitempty"`
	// url for the stack
	Url NullableString `json:"url,omitempty"`
}

type _InternalStackCreateRequestV1 InternalStackCreateRequestV1

// NewInternalStackCreateRequestV1 instantiates a new InternalStackCreateRequestV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalStackCreateRequestV1(name string, org string, region string, slug string) *InternalStackCreateRequestV1 {
	this := InternalStackCreateRequestV1{}
	var deleteProtection bool = true
	this.DeleteProtection = &deleteProtection
	this.Name = name
	this.Org = org
	this.Region = region
	this.Slug = slug
	return &this
}

// NewInternalStackCreateRequestV1WithDefaults instantiates a new InternalStackCreateRequestV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalStackCreateRequestV1WithDefaults() *InternalStackCreateRequestV1 {
	this := InternalStackCreateRequestV1{}
	var deleteProtection bool = true
	this.DeleteProtection = &deleteProtection
	return &this
}

// GetDeleteProtection returns the DeleteProtection field value if set, zero value otherwise.
func (o *InternalStackCreateRequestV1) GetDeleteProtection() bool {
	if o == nil || IsNil(o.DeleteProtection) {
		var ret bool
		return ret
	}
	return *o.DeleteProtection
}

// GetDeleteProtectionOk returns a tuple with the DeleteProtection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalStackCreateRequestV1) GetDeleteProtectionOk() (*bool, bool) {
	if o == nil || IsNil(o.DeleteProtection) {
		return nil, false
	}
	return o.DeleteProtection, true
}

// HasDeleteProtection returns a boolean if a field has been set.
func (o *InternalStackCreateRequestV1) HasDeleteProtection() bool {
	if o != nil && !IsNil(o.DeleteProtection) {
		return true
	}

	return false
}

// SetDeleteProtection gets a reference to the given bool and assigns it to the DeleteProtection field.
func (o *InternalStackCreateRequestV1) SetDeleteProtection(v bool) {
	o.DeleteProtection = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalStackCreateRequestV1) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalStackCreateRequestV1) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *InternalStackCreateRequestV1) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *InternalStackCreateRequestV1) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *InternalStackCreateRequestV1) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *InternalStackCreateRequestV1) UnsetDescription() {
	o.Description.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *InternalStackCreateRequestV1) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalStackCreateRequestV1) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *InternalStackCreateRequestV1) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *InternalStackCreateRequestV1) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetName returns the Name field value
func (o *InternalStackCreateRequestV1) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InternalStackCreateRequestV1) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InternalStackCreateRequestV1) SetName(v string) {
	o.Name = v
}

// GetOrg returns the Org field value
func (o *InternalStackCreateRequestV1) GetOrg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Org
}

// GetOrgOk returns a tuple with the Org field value
// and a boolean to check if the value has been set.
func (o *InternalStackCreateRequestV1) GetOrgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Org, true
}

// SetOrg sets field value
func (o *InternalStackCreateRequestV1) SetOrg(v string) {
	o.Org = v
}

// GetPlugins returns the Plugins field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalStackCreateRequestV1) GetPlugins() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Plugins
}

// GetPluginsOk returns a tuple with the Plugins field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalStackCreateRequestV1) GetPluginsOk() ([]string, bool) {
	if o == nil || IsNil(o.Plugins) {
		return nil, false
	}
	return o.Plugins, true
}

// HasPlugins returns a boolean if a field has been set.
func (o *InternalStackCreateRequestV1) HasPlugins() bool {
	if o != nil && IsNil(o.Plugins) {
		return true
	}

	return false
}

// SetPlugins gets a reference to the given []string and assigns it to the Plugins field.
func (o *InternalStackCreateRequestV1) SetPlugins(v []string) {
	o.Plugins = v
}

// GetRegion returns the Region field value
func (o *InternalStackCreateRequestV1) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *InternalStackCreateRequestV1) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *InternalStackCreateRequestV1) SetRegion(v string) {
	o.Region = v
}

// GetSlug returns the Slug field value
func (o *InternalStackCreateRequestV1) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *InternalStackCreateRequestV1) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *InternalStackCreateRequestV1) SetSlug(v string) {
	o.Slug = v
}

// GetTrialExpiresAt returns the TrialExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalStackCreateRequestV1) GetTrialExpiresAt() time.Time {
	if o == nil || IsNil(o.TrialExpiresAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.TrialExpiresAt.Get()
}

// GetTrialExpiresAtOk returns a tuple with the TrialExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalStackCreateRequestV1) GetTrialExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrialExpiresAt.Get(), o.TrialExpiresAt.IsSet()
}

// HasTrialExpiresAt returns a boolean if a field has been set.
func (o *InternalStackCreateRequestV1) HasTrialExpiresAt() bool {
	if o != nil && o.TrialExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetTrialExpiresAt gets a reference to the given NullableTime and assigns it to the TrialExpiresAt field.
func (o *InternalStackCreateRequestV1) SetTrialExpiresAt(v time.Time) {
	o.TrialExpiresAt.Set(&v)
}

// SetTrialExpiresAtNil sets the value for TrialExpiresAt to be an explicit nil
func (o *InternalStackCreateRequestV1) SetTrialExpiresAtNil() {
	o.TrialExpiresAt.Set(nil)
}

// UnsetTrialExpiresAt ensures that no value is present for TrialExpiresAt, not even an explicit nil
func (o *InternalStackCreateRequestV1) UnsetTrialExpiresAt() {
	o.TrialExpiresAt.Unset()
}

// GetUrl returns the Url field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalStackCreateRequestV1) GetUrl() string {
	if o == nil || IsNil(o.Url.Get()) {
		var ret string
		return ret
	}
	return *o.Url.Get()
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalStackCreateRequestV1) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Url.Get(), o.Url.IsSet()
}

// HasUrl returns a boolean if a field has been set.
func (o *InternalStackCreateRequestV1) HasUrl() bool {
	if o != nil && o.Url.IsSet() {
		return true
	}

	return false
}

// SetUrl gets a reference to the given NullableString and assigns it to the Url field.
func (o *InternalStackCreateRequestV1) SetUrl(v string) {
	o.Url.Set(&v)
}

// SetUrlNil sets the value for Url to be an explicit nil
func (o *InternalStackCreateRequestV1) SetUrlNil() {
	o.Url.Set(nil)
}

// UnsetUrl ensures that no value is present for Url, not even an explicit nil
func (o *InternalStackCreateRequestV1) UnsetUrl() {
	o.Url.Unset()
}

func (o InternalStackCreateRequestV1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalStackCreateRequestV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeleteProtection) {
		toSerialize["deleteProtection"] = o.DeleteProtection
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	toSerialize["name"] = o.Name
	toSerialize["org"] = o.Org
	if o.Plugins != nil {
		toSerialize["plugins"] = o.Plugins
	}
	toSerialize["region"] = o.Region
	toSerialize["slug"] = o.Slug
	if o.TrialExpiresAt.IsSet() {
		toSerialize["trialExpiresAt"] = o.TrialExpiresAt.Get()
	}
	if o.Url.IsSet() {
		toSerialize["url"] = o.Url.Get()
	}
	return toSerialize, nil
}

func (o *InternalStackCreateRequestV1) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varInternalStackCreateRequestV1 := _InternalStackCreateRequestV1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varInternalStackCreateRequestV1)

	if err != nil {
		return err
	}

	*o = InternalStackCreateRequestV1(varInternalStackCreateRequestV1)

	return err
}

type NullableInternalStackCreateRequestV1 struct {
	value *InternalStackCreateRequestV1
	isSet bool
}

func (v NullableInternalStackCreateRequestV1) Get() *InternalStackCreateRequestV1 {
	return v.value
}

func (v *NullableInternalStackCreateRequestV1) Set(val *InternalStackCreateRequestV1) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalStackCreateRequestV1) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalStackCreateRequestV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalStackCreateRequestV1(val *InternalStackCreateRequestV1) *NullableInternalStackCreateRequestV1 {
	return &NullableInternalStackCreateRequestV1{value: val, isSet: true}
}

func (v NullableInternalStackCreateRequestV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalStackCreateRequestV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
