/*
GCOM API

Grafana.com API (public).  Looking for GCOM API client packages? You can find them at [grafana-com-public-clients](https://github.com/grafana/grafana-com-public-clients) repository.  If you have any questions, please contact support in the Grafana Cloud UI.  This spec is in *Beta* stage, so use it with caution: - Not all endpoint responses are properly typed for the time being. - Some request parameter types may not be precise

API version: public
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner{}

// PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner struct for PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner
type PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner struct {
	Selector             string `json:"selector"`
	AdditionalProperties map[string]interface{}
}

type _PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner

// NewPostAccessPoliciesRequestRealmsInnerLabelPoliciesInner instantiates a new PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostAccessPoliciesRequestRealmsInnerLabelPoliciesInner(selector string) *PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner {
	this := PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner{}
	this.Selector = selector
	return &this
}

// NewPostAccessPoliciesRequestRealmsInnerLabelPoliciesInnerWithDefaults instantiates a new PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostAccessPoliciesRequestRealmsInnerLabelPoliciesInnerWithDefaults() *PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner {
	this := PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner{}
	return &this
}

// GetSelector returns the Selector field value
func (o *PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner) GetSelector() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Selector
}

// GetSelectorOk returns a tuple with the Selector field value
// and a boolean to check if the value has been set.
func (o *PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner) GetSelectorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Selector, true
}

// SetSelector sets field value
func (o *PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner) SetSelector(v string) {
	o.Selector = v
}

func (o PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["selector"] = o.Selector

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varPostAccessPoliciesRequestRealmsInnerLabelPoliciesInner := _PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner{}

	err = json.Unmarshal(data, &varPostAccessPoliciesRequestRealmsInnerLabelPoliciesInner)

	if err != nil {
		return err
	}

	*o = PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner(varPostAccessPoliciesRequestRealmsInnerLabelPoliciesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "selector")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePostAccessPoliciesRequestRealmsInnerLabelPoliciesInner struct {
	value *PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner
	isSet bool
}

func (v NullablePostAccessPoliciesRequestRealmsInnerLabelPoliciesInner) Get() *PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner {
	return v.value
}

func (v *NullablePostAccessPoliciesRequestRealmsInnerLabelPoliciesInner) Set(val *PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePostAccessPoliciesRequestRealmsInnerLabelPoliciesInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePostAccessPoliciesRequestRealmsInnerLabelPoliciesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostAccessPoliciesRequestRealmsInnerLabelPoliciesInner(val *PostAccessPoliciesRequestRealmsInnerLabelPoliciesInner) *NullablePostAccessPoliciesRequestRealmsInnerLabelPoliciesInner {
	return &NullablePostAccessPoliciesRequestRealmsInnerLabelPoliciesInner{value: val, isSet: true}
}

func (v NullablePostAccessPoliciesRequestRealmsInnerLabelPoliciesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostAccessPoliciesRequestRealmsInnerLabelPoliciesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
