/*
GCOM API

Grafana.com API (public).  Looking for GCOM API client packages? You can find them at [grafana-com-public-clients](https://github.com/grafana/grafana-com-public-clients) repository.  If you have any questions, please contact support in the Grafana Cloud UI.  This spec is in *Beta* stage, so use it with caution: - Not all endpoint responses are properly typed for the time being. - Some request parameter types may not be precise

API version: public
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the FormattedApiApiKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FormattedApiApiKey{}

// FormattedApiApiKey struct for FormattedApiApiKey
type FormattedApiApiKey struct {
	Id                   *FormattedApiApiKeyId `json:"id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FormattedApiApiKey FormattedApiApiKey

// NewFormattedApiApiKey instantiates a new FormattedApiApiKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFormattedApiApiKey() *FormattedApiApiKey {
	this := FormattedApiApiKey{}
	return &this
}

// NewFormattedApiApiKeyWithDefaults instantiates a new FormattedApiApiKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFormattedApiApiKeyWithDefaults() *FormattedApiApiKey {
	this := FormattedApiApiKey{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FormattedApiApiKey) GetId() FormattedApiApiKeyId {
	if o == nil || IsNil(o.Id) {
		var ret FormattedApiApiKeyId
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FormattedApiApiKey) GetIdOk() (*FormattedApiApiKeyId, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FormattedApiApiKey) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given FormattedApiApiKeyId and assigns it to the Id field.
func (o *FormattedApiApiKey) SetId(v FormattedApiApiKeyId) {
	o.Id = &v
}

func (o FormattedApiApiKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FormattedApiApiKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FormattedApiApiKey) UnmarshalJSON(data []byte) (err error) {
	varFormattedApiApiKey := _FormattedApiApiKey{}

	err = json.Unmarshal(data, &varFormattedApiApiKey)

	if err != nil {
		return err
	}

	*o = FormattedApiApiKey(varFormattedApiApiKey)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFormattedApiApiKey struct {
	value *FormattedApiApiKey
	isSet bool
}

func (v NullableFormattedApiApiKey) Get() *FormattedApiApiKey {
	return v.value
}

func (v *NullableFormattedApiApiKey) Set(val *FormattedApiApiKey) {
	v.value = val
	v.isSet = true
}

func (v NullableFormattedApiApiKey) IsSet() bool {
	return v.isSet
}

func (v *NullableFormattedApiApiKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFormattedApiApiKey(val *FormattedApiApiKey) *NullableFormattedApiApiKey {
	return &NullableFormattedApiApiKey{value: val, isSet: true}
}

func (v NullableFormattedApiApiKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFormattedApiApiKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
