/*
GCOM API

Grafana.com API (public).  Looking for GCOM API client packages? You can find them at [grafana-com-public-clients](https://github.com/grafana/grafana-com-public-clients) repository.  If you have any questions, please contact support in the Grafana Cloud UI.  This spec is in *Beta* stage, so use it with caution: - Not all endpoint responses are properly typed for the time being. - Some request parameter types may not be precise

API version: public
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
	"time"
)

// checks if the Current2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Current2{}

// Current2 struct for Current2
type Current2 struct {
	Product                string         `json:"product"`
	IsTrial                bool           `json:"isTrial"`
	StartDate              time.Time      `json:"startDate"`
	EndDate                interface{}    `json:"endDate"`
	Payload                Payload        `json:"payload"`
	Plan                   NullableString `json:"plan"`
	PublicName             NullableString `json:"publicName"`
	EnterprisePluginsAdded bool           `json:"enterprisePluginsAdded"`
	PlanBillingCycle       string         `json:"planBillingCycle"`
	AdditionalProperties   map[string]interface{}
}

type _Current2 Current2

// NewCurrent2 instantiates a new Current2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurrent2(product string, isTrial bool, startDate time.Time, endDate interface{}, payload Payload, plan NullableString, publicName NullableString, enterprisePluginsAdded bool, planBillingCycle string) *Current2 {
	this := Current2{}
	this.Product = product
	this.IsTrial = isTrial
	this.StartDate = startDate
	this.EndDate = endDate
	this.Payload = payload
	this.Plan = plan
	this.PublicName = publicName
	this.EnterprisePluginsAdded = enterprisePluginsAdded
	this.PlanBillingCycle = planBillingCycle
	return &this
}

// NewCurrent2WithDefaults instantiates a new Current2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurrent2WithDefaults() *Current2 {
	this := Current2{}
	return &this
}

// GetProduct returns the Product field value
func (o *Current2) GetProduct() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Product
}

// GetProductOk returns a tuple with the Product field value
// and a boolean to check if the value has been set.
func (o *Current2) GetProductOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Product, true
}

// SetProduct sets field value
func (o *Current2) SetProduct(v string) {
	o.Product = v
}

// GetIsTrial returns the IsTrial field value
func (o *Current2) GetIsTrial() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsTrial
}

// GetIsTrialOk returns a tuple with the IsTrial field value
// and a boolean to check if the value has been set.
func (o *Current2) GetIsTrialOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsTrial, true
}

// SetIsTrial sets field value
func (o *Current2) SetIsTrial(v bool) {
	o.IsTrial = v
}

// GetStartDate returns the StartDate field value
func (o *Current2) GetStartDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value
// and a boolean to check if the value has been set.
func (o *Current2) GetStartDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartDate, true
}

// SetStartDate sets field value
func (o *Current2) SetStartDate(v time.Time) {
	o.StartDate = v
}

// GetEndDate returns the EndDate field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *Current2) GetEndDate() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Current2) GetEndDateOk() (*interface{}, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return &o.EndDate, true
}

// SetEndDate sets field value
func (o *Current2) SetEndDate(v interface{}) {
	o.EndDate = v
}

// GetPayload returns the Payload field value
func (o *Current2) GetPayload() Payload {
	if o == nil {
		var ret Payload
		return ret
	}

	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value
// and a boolean to check if the value has been set.
func (o *Current2) GetPayloadOk() (*Payload, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Payload, true
}

// SetPayload sets field value
func (o *Current2) SetPayload(v Payload) {
	o.Payload = v
}

// GetPlan returns the Plan field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Current2) GetPlan() string {
	if o == nil || o.Plan.Get() == nil {
		var ret string
		return ret
	}

	return *o.Plan.Get()
}

// GetPlanOk returns a tuple with the Plan field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Current2) GetPlanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Plan.Get(), o.Plan.IsSet()
}

// SetPlan sets field value
func (o *Current2) SetPlan(v string) {
	o.Plan.Set(&v)
}

// GetPublicName returns the PublicName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Current2) GetPublicName() string {
	if o == nil || o.PublicName.Get() == nil {
		var ret string
		return ret
	}

	return *o.PublicName.Get()
}

// GetPublicNameOk returns a tuple with the PublicName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Current2) GetPublicNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PublicName.Get(), o.PublicName.IsSet()
}

// SetPublicName sets field value
func (o *Current2) SetPublicName(v string) {
	o.PublicName.Set(&v)
}

// GetEnterprisePluginsAdded returns the EnterprisePluginsAdded field value
func (o *Current2) GetEnterprisePluginsAdded() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EnterprisePluginsAdded
}

// GetEnterprisePluginsAddedOk returns a tuple with the EnterprisePluginsAdded field value
// and a boolean to check if the value has been set.
func (o *Current2) GetEnterprisePluginsAddedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnterprisePluginsAdded, true
}

// SetEnterprisePluginsAdded sets field value
func (o *Current2) SetEnterprisePluginsAdded(v bool) {
	o.EnterprisePluginsAdded = v
}

// GetPlanBillingCycle returns the PlanBillingCycle field value
func (o *Current2) GetPlanBillingCycle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanBillingCycle
}

// GetPlanBillingCycleOk returns a tuple with the PlanBillingCycle field value
// and a boolean to check if the value has been set.
func (o *Current2) GetPlanBillingCycleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanBillingCycle, true
}

// SetPlanBillingCycle sets field value
func (o *Current2) SetPlanBillingCycle(v string) {
	o.PlanBillingCycle = v
}

func (o Current2) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Current2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["product"] = o.Product
	toSerialize["isTrial"] = o.IsTrial
	toSerialize["startDate"] = o.StartDate
	if o.EndDate != nil {
		toSerialize["endDate"] = o.EndDate
	}
	toSerialize["payload"] = o.Payload
	toSerialize["plan"] = o.Plan.Get()
	toSerialize["publicName"] = o.PublicName.Get()
	toSerialize["enterprisePluginsAdded"] = o.EnterprisePluginsAdded
	toSerialize["planBillingCycle"] = o.PlanBillingCycle

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Current2) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varCurrent2 := _Current2{}

	err = json.Unmarshal(data, &varCurrent2)

	if err != nil {
		return err
	}

	*o = Current2(varCurrent2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "product")
		delete(additionalProperties, "isTrial")
		delete(additionalProperties, "startDate")
		delete(additionalProperties, "endDate")
		delete(additionalProperties, "payload")
		delete(additionalProperties, "plan")
		delete(additionalProperties, "publicName")
		delete(additionalProperties, "enterprisePluginsAdded")
		delete(additionalProperties, "planBillingCycle")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCurrent2 struct {
	value *Current2
	isSet bool
}

func (v NullableCurrent2) Get() *Current2 {
	return v.value
}

func (v *NullableCurrent2) Set(val *Current2) {
	v.value = val
	v.isSet = true
}

func (v NullableCurrent2) IsSet() bool {
	return v.isSet
}

func (v *NullableCurrent2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurrent2(val *Current2) *NullableCurrent2 {
	return &NullableCurrent2{value: val, isSet: true}
}

func (v NullableCurrent2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurrent2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
