compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmPublishRegistry: "https://us-npm.pkg.dev/grafanalabs-dev/cloud-npm-dev"

npmRegistries:
  "https://us-npm.pkg.dev/grafanalabs-dev/cloud-npm-dev":
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN-}"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
