name: Generate Clients

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 1.26.3
      - name: Generate Client
        uses: grafana/shared-workflows/actions/generate-openapi-clients@e5b7989c92b55fe3ac6dd006d6de49082ba8c507
        with:
          package-name: gcom
          spec-path: openapi.json
          modify-spec-script: .github/workflows/modify-spec.sh
          commit-changes: "false"
        env:
          REPO_NAME: grafana-com-public-clients
      - name: Pin Go module version
        shell: bash
        run: |
          cd go/gcom
          go mod edit -go=1.26.3
          go mod tidy
      - name: Commit changes
        if: github.event_name == 'pull_request'
        uses: planetscale/ghcommit-action@a6b150b81dca5dd027baa898604418eec9e11465 # v0.2.22
        with:
          commit_message: Updating generated clients after openapi change
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref }}
          file_pattern: go/gcom
